- platform: ping
  hosts:
    raspberry: !secret raspberry
    iPhone: !secret iPhone
    AppleWatchDenis: !secret AppleWatchDenis

- platform: nmap_tracker
  interval_seconds: 30
  hosts: 10.0.1.200-254
  home_interval: 2
  new_device_defaults:
    track_new_devices: false
    hide_if_away: true