resources:
  - url: /local/bar-card.js
    type: js
  - url: /local/custom-weather-card-chart.js
    type: module
  - url: /local/mini-graph-card-bundle.js
    type: module
  - url: /local/tracker-card.js?track=true
    type: module
  - url: /local/vertical-stack-in-card.js?v=v0.1.1
    type: js
  - url: /local/battery-entity.js?v=0.2
    type: module
  - url: /local/simple-weather-card.bundle.js?v=0.3.0
    type: module
  - url: /local/weather-card.js
    type: module
  - url: /local/tiles-card.js?v=0.1
    type: js

name: Our home 
views:
- title: Дом
  id: main
  icon: mdi:home
  columns: 1
  cards:
  - type: entities
    show_header_toggle: false
    title: Cabinet
    entities:
      - entity: light.cabinet_desk_lamp
      - entity: input_boolean.auto_turn_off_cabinet_desk_lamp
      - type: divider
      - entity: script.set_cabinet_desk_lamp_custom
        tap_action: 
          action: toggle
        name: Warm 70%
        icon: mdi:desk-lamp
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        name: GreenHouse temperature
        hours_to_show: 12
        line_color: '#63b068'
        extrema: true
        labels: true
        line_width: 3
        points_per_hour: 1
        decimals: 1
        hour24: true
        entities:
          - sensor.temperature_2
      - type: entities
        show_header_toggle: false
        title: GreenHouse
        entities:
          - entity: sensor.temperature_2
            name: Temperature
          - entity: sensor.humidity_3
            name: Humidity
          - entity: sensor.pressure_4
            name: Pressure
  - type: entities
    show_header_toggle: false
    title: Baby room
    entities:
    - entity: light.baby_room_floor_lamp
      name: Floor lamp
      icon: mdi:floor-lamp
    - entity: input_boolean.auto_turn_off_baby_floor_lamp
  - type: entities
    show_header_toggle: false
    title: Outdoor lights
    entities:
      - entity: light.light_outdoor
      - entity: input_boolean.auto_turn_on_off_by_sunset_sunrise
  - type: entities
    show_header_toggle: false
    title: Stairway
    entities:
      - entity: light.hall_light_2
      - entity: light.gateway_light_7811dcfadbf9
      - entity: input_boolean.auto_turn_on_nightlight_with_motion
  - type: entities
    show_header_toggle: false
    title: Others
    entities:
      - entity: switch.imac_power
      - entity: device_tracker.b0_19_c6_a5_b8_0f
      - entity: device_tracker.34_7c_25_c3_b6_e2
      - entity: sensor.ha_installed_version
      - entity: sensor.ha_latest_version
  - type: custom:weather-card
    entity: weather.dark_sky
    icons: "/local/icons/"