- alias: Turn ON light
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.cabinet_desk_lamp

# Cabinet_Desk_lamp
- alias: did change state auto turn off cabinet desk lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.auto_turn_off_cabinet_desk_lamp
    to: 'on'
  action:
    - service: script.cabinet_desk_lamp_turned_off_5min

- alias: did change state cabinet desk lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: light.cabinet_desk_lamp
    to: 'on'
  action:
    - service: script.cabinet_desk_lamp_turned_off_5min

# Baby_room_Floor_lamp
- alias: did change state auto turn off baby floor lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.auto_turn_off_baby_floor_lamp
    to: 'on'
  action:
    - service: script.baby_floor_lamp_turned_off_5min

- alias: did change state baby room floor lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: light.baby_room_floor_lamp
    to: 'on'
  action:
    - service: script.baby_floor_lamp_turned_off_5min

# Outdoor light
- alias: turn on outdoor light after sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.outdoor_light
  
- alias: turn off outdoor light after sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: switch.outdoor_light

- alias: If there is motion and its dark turn on the gateway light
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d000208e2ef
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.illumination_7811dcfadbf9
        below: 200
      - condition: state
        entity_id: input_boolean.auto_turn_on_nightlight_with_motion
        state: 'on'
      - condition: time
        after: '20:45:00'
        before: '02:00:00'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_7811dcfadbf9
      data_template:
        brightness: 42
        rgb_color: [255,127,0]
    - delay: 00:00:30
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcfadbf9