- alias: Desktop lamp turn off when iMac locked
  trigger:
    platform: state
    entity_id: switch.imac_power
    to: 'off'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.cabinet_desk_lamp

- alias: Desktop lamp turn on when iMac unlocked
  trigger:
    platform: state
    entity_id: switch.imac_power
    to: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.cabinet_desk_lamp

# - alias: Cabinet desktop lamp turn on when low lightlevel and motion detected
#   trigger:
#     platform: state
#     entity_id: binary_sensor.presence_5
#     to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: numeric_state
#         entity_id: sensor.lightlevel_6
#         below: 10
#   action:
#     - service: light.turn_on
#       data_template:
#         entity_id: light.cabinet_desk_lamp

# Motion sensor on stairway
- alias: If there is motion and its dark turn on the gateway light
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_7
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.illumination_7811dcfadbf9
        below: 300
      - condition: state
        entity_id: input_boolean.auto_turn_on_nightlight_with_motion
        state: 'on'
      - condition: time
        after: '20:00:00'
        before: '04:00:00'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_7811dcfadbf9
      data_template:
        brightness: 42
        rgb_color: [255,127,0]
    - delay: 00:00:15
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcfadbf9

# Cabinet_Desk_lamp
- alias: did change state auto turn off cabinet desk lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.auto_turn_off_cabinet_desk_lamp
    to: 'on'
  action:
    - service: script.cabinet_desk_lamp_turned_off_5min

- alias: did change state cabinet desk lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: light.cabinet_desk_lamp
    to: 'on'
  action:
    - service: script.cabinet_desk_lamp_turned_off_5min

# Baby_room_Floor_lamp
- alias: did change state auto turn off baby floor lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.auto_turn_off_baby_floor_lamp
    to: 'on'
  action:
    - service: script.baby_floor_lamp_turned_off_5min

- alias: did change state baby room floor lamp
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: light.baby_room_floor_lamp
    to: 'on'
  action:
    - service: script.baby_floor_lamp_turned_off_5min

  # Outdoor light
- alias: turn on outdoor light after sunset
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      entity_id: light.light_outdoor
    - service: notify.telegram
      data_template:
        message: "Event: sun in sunset"
  
- alias: turn off outdoor light after sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.light_outdoor
    - service: notify.telegram
      data_template:
        message: "Event: sun in sunrise"