- alias: system_start_message
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F603 Сервер запущен!"

- alias: system_stop_message
  initial_state: 'on'
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F621 Сервер остановлен!"

- alias: system_new_device_found
  initial_state: 'on'
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.telegram
      data_template: 
        message: "\U00002734 Новое устройство - {{trigger.event.data.host_name}} - ({{trigger.event.data.entity_id}})"

- alias: system_hassio_new_version
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.telegram
      data_template: 
        message: "\U00002733 {{ states.updater.updater.state }} доступен!"
