# Sensors
- platform: command_line
  name: CPU Temp
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '°C'
  value_template: '{{ value | multiply(0.001) }}'

# HA Installed version sensor
- platform: version
  name: HA Installed Version
  scan_interval: 1800

# HA Latest version sensor
- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/stable.json
  name: HA Latest Version
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 1800